### ISSUE TITLE
fbauth2:/" - error: "The operation couldn’t be completed

### ISSUE THREAD

**Issue by gpfiel** [NativeScript/nativescript-facebook#63] opened 2017-08-17 13:28 UTC
Hi, Thanks for the plugin. I am trying to install it on an IOS device but the error below appears:

`-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"`

1. Everything was installed following the readme
2. When I click on the button (customized) to login, the facebook page appears.
3. The credentials are filled
4. The error appears and a blank page is shown 
5. So I click done and the alert send me "Error during login: canceled"
 
Do you have any idea what is wrong? Maybe I did something wrong.

Thanks in advance!

**Comment by radeva** [comment] 2017-08-17 14:12
Hi @gpfiel,

Have you checked the demo apps in this repository? They might help you structure your code correctly. If this doesn't help, can you send us an example app as a .zip or refer to a repository with an app where the problem can be reproduced? Also it will help a lot if you tell us:

- what version of NativeScript you're using (run `tns --version` and send us the result)
- what version of the iOS you're using

Best regards,
Veselina

**Comment by radeva** [comment] 2017-08-18 16:06
I'm closing this since it more or less duplicates what's in #65

**Closed by radeva** 2017-08-18 16:06 UTC
Labels: question
